#page title
page_title                                : Markerpad                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.microsoft.com/detail/9NH0WPDRK28T?cid=markerpadsite                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Markerpad                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ideas to formulas, notes to diagrams. Markerpad is a canvas for every need.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jenius Apps                              
your_link                                 : https://apps.microsoft.com/detail/9NH0WPDRK28T?cid=markerpadsite                  
your_city                                 : Vancouver, Canada                                
email_address                             : jenius_apps@outlook.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : dpaulino
youtube_username                          : 
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your digital scratchpad
    description                           : Use Markerpad for drawings, diagrams, ideas, or small notes. Anything you can imagine.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Faster than light
    description                           : Markerpad is designed for performance to keep up with your creativity.
    fontawesome_icon_name                 : bolt
    
  - title                                 : Auto-saves locally
    description                           : Your work is saved offline and automatically. Reliable and zero friction.
    fontawesome_icon_name                 : save

  - title                                 : Cloud backup
    description                           : Never lose your notes with available hassle-free backup.
    fontawesome_icon_name                 : cloud

  - title                                 : Designed for Pen
    description                           : Supports left- and right-hand pen users, and can align with your OS settings.
    fontawesome_icon_name                 : pen
  
  - title                                 : Modern Windows design
    description                           : Inspired by the Fluent Design system, Markerpad shines on Windows 11.
    fontawesome_icon_name                 : laptop


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
